import { Project } from '../types';

export const SAMPLE_PROJECT: Project = {
  id: 'proj_sample_01',
  title: 'O Mistério da Inteligência Artificial',
  description: 'Vídeo explicativo sobre o impacto e o futuro da IA no mundo digital.',
  rawScript: `Você já parou para pensar como a Inteligência Artificial está transformando a nossa vida cotidiana?
Em poucos anos, o que parecia ficção científica se tornou parte da nossa rotina.
Desde a criação de conteúdo até o diagnóstico médico, a IA está redefinindo as fronteiras do conhecimento.
E o futuro? Ele está sendo escrito agora mesmo, linha por linha de código!`,
  settings: {
    aspectRatio: '9:16',
    resolution: '1080p',
    language: 'Português',
    defaultVoiceId: 'valentino',
    globalVisualStyle: 'Cinematográfico moderno, iluminação neon dramática, iluminação de estúdio 8k',
  },
  scenes: [
    {
      id: 'scene_1',
      order: 1,
      title: 'Cena 1: A Revolução Silenciosa',
      narrationText: 'Você já parou para pensar como a Inteligência Artificial está transformando a nossa vida cotidiana?',
      estimatedDurationSec: 5,
      actualDurationSec: 5,
      visualPrompt: 'Pessoa contemplativa observando uma cidade futurista à noite com linhas digitais e luzes neon reluzentes, 8k cinematográfico.',
      negativePrompt: 'desfocado, baixa qualidade, desenho infantil',
      characterIds: ['char_main'],
      locationId: 'loc_city',
      transitionOut: 'dissolve',
      visualStyle: 'Cinematográfico Futurista',
      imageMediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&h=1920&q=80',
      status: 'completed',
    },
    {
      id: 'scene_2',
      order: 2,
      title: 'Cena 2: Da Ficção à Realidade',
      narrationText: 'Em poucos anos, o que parecia ficção científica se tornou parte da nossa rotina.',
      estimatedDurationSec: 4.5,
      actualDurationSec: 4.5,
      visualPrompt: 'Interface holográfica brilhante sendo manipulada por mãos humanas em um laboratório tecnológico de ponta.',
      negativePrompt: 'baixa resolução, borrado, marca d\'água',
      characterIds: ['char_main'],
      locationId: 'loc_lab',
      transitionOut: 'slide_left',
      visualStyle: 'Tech Glow',
      imageMediaUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1080&h=1920&q=80',
      status: 'completed',
    },
    {
      id: 'scene_3',
      order: 3,
      title: 'Cena 3: Fronteiras do Conhecimento',
      narrationText: 'Desde a criação de conteúdo até o diagnóstico médico, a IA está redefinindo as fronteiras do conhecimento.',
      estimatedDurationSec: 6,
      actualDurationSec: 6,
      visualPrompt: 'Conexões neurais em 3D brilhando em tons de azul e violeta, simbolizando aprendizado profundo de máquina.',
      negativePrompt: 'escuro demais, feio',
      characterIds: [],
      locationId: 'loc_abstract',
      transitionOut: 'blur_transition',
      visualStyle: 'Abstrato Neural',
      imageMediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1080&h=1920&q=80',
      status: 'completed',
    },
    {
      id: 'scene_4',
      order: 4,
      title: 'Cena 4: O Futuro é Agora',
      narrationText: 'E o futuro? Ele está sendo escrito agora mesmo, linha por linha de código!',
      estimatedDurationSec: 5,
      actualDurationSec: 5,
      visualPrompt: 'Visão panorâmica de um nascer do sol brilhante em uma metrópole tecnológica sustentável do amanhã.',
      negativePrompt: 'ruído, ruínas',
      characterIds: ['char_main'],
      locationId: 'loc_city',
      transitionOut: 'fade_black',
      visualStyle: 'Cinematográfico Épico',
      imageMediaUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1080&h=1920&q=80',
      status: 'completed',
    },
  ],
  captions: {
    id: 'cap_track_01',
    style: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 24,
      color: '#FFFFFF',
      outlineColor: '#000000',
      outlineWidth: 3,
      backgroundColor: '#000000AA',
      backgroundPadding: 8,
      shadow: true,
      positionY: 'bottom',
      highlightColor: '#FFE600',
      textTransform: 'uppercase',
    },
    cues: [
      {
        id: 'cue_1',
        sceneId: 'scene_1',
        text: 'Você já parou para pensar como a IA está transformando nossa vida?',
        startTimeSec: 0,
        endTimeSec: 5,
        words: [
          { word: 'Você', startTimeSec: 0, endTimeSec: 0.6 },
          { word: 'já', startTimeSec: 0.6, endTimeSec: 1.0 },
          { word: 'parou', startTimeSec: 1.0, endTimeSec: 1.5 },
          { word: 'para', startTimeSec: 1.5, endTimeSec: 1.8 },
          { word: 'pensar', startTimeSec: 1.8, endTimeSec: 2.3 },
          { word: 'como', startTimeSec: 2.3, endTimeSec: 2.7 },
          { word: 'a IA', startTimeSec: 2.7, endTimeSec: 3.2 },
          { word: 'está', startTimeSec: 3.2, endTimeSec: 3.6 },
          { word: 'transformando', startTimeSec: 3.6, endTimeSec: 4.3 },
          { word: 'nossa vida?', startTimeSec: 4.3, endTimeSec: 5.0 },
        ],
      },
      {
        id: 'cue_2',
        sceneId: 'scene_2',
        text: 'Em poucos anos, o que parecia ficção se tornou rotina.',
        startTimeSec: 5,
        endTimeSec: 9.5,
      },
      {
        id: 'cue_3',
        sceneId: 'scene_3',
        text: 'A IA redefine as fronteiras do conhecimento.',
        startTimeSec: 9.5,
        endTimeSec: 15.5,
      },
      {
        id: 'cue_4',
        sceneId: 'scene_4',
        text: 'O futuro está sendo escrito agora mesmo!',
        startTimeSec: 15.5,
        endTimeSec: 20.5,
      },
    ],
  },
  timeline: {
    durationSec: 20.5,
    currentTimeSec: 0,
    tracks: [
      {
        id: 'track_video_1',
        type: 'video',
        title: 'Vídeo Principal (IA)',
        isMuted: false,
        isLocked: false,
        isHidden: false,
        clips: [
          { id: 'clip_v1', trackId: 'track_video_1', sceneId: 'scene_1', name: 'Revolução Silenciosa', type: 'image', startTimeSec: 0, durationSec: 5, sourceUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&h=1920&q=80', color: 'bg-indigo-600' },
          { id: 'clip_v2', trackId: 'track_video_1', sceneId: 'scene_2', name: 'Ficção e Realidade', type: 'image', startTimeSec: 5, durationSec: 4.5, sourceUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1080&h=1920&q=80', color: 'bg-purple-600' },
          { id: 'clip_v3', trackId: 'track_video_1', sceneId: 'scene_3', name: 'Fronteiras', type: 'image', startTimeSec: 9.5, durationSec: 6, sourceUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1080&h=1920&q=80', color: 'bg-blue-600' },
          { id: 'clip_v4', trackId: 'track_video_1', sceneId: 'scene_4', name: 'O Futuro é Agora', type: 'image', startTimeSec: 15.5, durationSec: 5, sourceUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1080&h=1920&q=80', color: 'bg-emerald-600' },
        ],
      },
      {
        id: 'track_captions_1',
        type: 'captions',
        title: 'Legendas Automáticas',
        isMuted: false,
        isLocked: false,
        isHidden: false,
        clips: [
          { id: 'clip_cap1', trackId: 'track_captions_1', name: 'Legenda #1', type: 'caption', startTimeSec: 0, durationSec: 5, color: 'bg-amber-600' },
          { id: 'clip_cap2', trackId: 'track_captions_1', name: 'Legenda #2', type: 'caption', startTimeSec: 5, durationSec: 4.5, color: 'bg-amber-600' },
          { id: 'clip_cap3', trackId: 'track_captions_1', name: 'Legenda #3', type: 'caption', startTimeSec: 9.5, durationSec: 6, color: 'bg-amber-600' },
          { id: 'clip_cap4', trackId: 'track_captions_1', name: 'Legenda #4', type: 'caption', startTimeSec: 15.5, durationSec: 5, color: 'bg-amber-600' },
        ],
      },
      {
        id: 'track_voice_1',
        type: 'voice',
        title: 'Narração (Valentino)',
        isMuted: false,
        isLocked: false,
        isHidden: false,
        clips: [
          { id: 'clip_audio1', trackId: 'track_voice_1', name: 'Narração Valentino', type: 'audio', startTimeSec: 0, durationSec: 20.5, color: 'bg-rose-600', volume: 1.0 },
        ],
      },
      {
        id: 'track_music_1',
        type: 'music',
        title: 'Trilha Sonora de Fundo',
        isMuted: false,
        isLocked: false,
        isHidden: false,
        clips: [
          { id: 'clip_mus1', trackId: 'track_music_1', name: 'Ambient Cyber Beat', type: 'audio', startTimeSec: 0, durationSec: 20.5, color: 'bg-teal-600', volume: 0.25 },
        ],
      },
    ],
  },
  mediaAssets: [
    {
      id: 'asset_1',
      name: 'Cidade Futurista.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&h=1920&q=80',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'asset_2',
      name: 'Interface Holográfica.jpg',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1080&h=1920&q=80',
      createdAt: new Date().toISOString(),
    },
  ],
  exportSettings: {
    filename: 'O_Misterio_da_Inteligencia_Artificial.mp4',
    resolution: '1080p',
    aspectRatio: '9:16',
    quality: 'Alta',
    frameRate: 30,
    burnInCaptions: true,
    includeWatermark: false,
  },
  thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&h=800&q=80',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  ownerId: 'user_local',
};
