import { VoiceStyle } from '../types';

export const VOICE_STYLES: VoiceStyle[] = [
  {
    id: 'valentino',
    name: 'Valentino',
    description: 'Narrador Elegante — estilo refinado, tom grave e cadência sofisticada para documentários e vídeos premium.',
    category: 'Cinematográfico',
    gender: 'male',
    tone: 'Sofisticado & Envolvente',
    defaultSpeed: 1.0,
    defaultPitch: 0.95,
    prebuiltVoiceName: 'Fenrir',
    avatarColor: 'from-amber-500 to-red-700',
    badge: 'Narrador Elegante',
  },
  {
    id: 'rayo',
    name: 'Rayo',
    description: 'Energia Rápida — tom jovem, dinâmico e acelerado, perfeito para Shorts, TikTok e conteúdos virais.',
    category: 'Redes Sociais',
    gender: 'male',
    tone: 'Vibrante & Acelerado',
    defaultSpeed: 1.2,
    defaultPitch: 1.05,
    prebuiltVoiceName: 'Zephyr',
    avatarColor: 'from-yellow-400 to-orange-600',
    badge: 'Energia Rápida',
  },
  {
    id: 'knightley',
    name: 'Knightley',
    description: 'Narrador Cinematográfico — voz profunda, épica e dramática para contação de histórias e trailers de impacto.',
    category: 'Épico',
    gender: 'male',
    tone: 'Dramático & Épico',
    defaultSpeed: 0.95,
    defaultPitch: 0.85,
    prebuiltVoiceName: 'Puck',
    avatarColor: 'from-blue-600 to-indigo-900',
    badge: 'Cinematográfico',
  },
  {
    id: 'nandez',
    name: 'Nandez',
    description: 'Comunicador Natural — tom amigável, autêntico e conversacional para vlogs, notícias e anúncios.',
    category: 'Conversacional',
    gender: 'male',
    tone: 'Natural & Empático',
    defaultSpeed: 1.05,
    defaultPitch: 1.0,
    prebuiltVoiceName: 'Charon',
    avatarColor: 'from-emerald-500 to-teal-800',
    badge: 'Comunicador Natural',
  },
  {
    id: 'mentora_estavel',
    name: 'Mentora Estável',
    description: 'Mentora Serena — tom firme, pausado e profissional para tutoriais, treinamentos e negócios.',
    category: 'Corporativo',
    gender: 'female',
    tone: 'Sereno & Autoridade',
    defaultSpeed: 0.98,
    defaultPitch: 0.95,
    prebuiltVoiceName: 'Kore',
    avatarColor: 'from-purple-600 to-indigo-800',
    badge: 'Mentora Serena',
  },
  {
    id: 'amelia',
    name: 'Amelia',
    description: 'Voz Feminina Acolhedora — tom caloroso, simpático e expressivo para narrações e estórias envolventes.',
    category: 'Acolhedor',
    gender: 'female',
    tone: 'Suave & Expressivo',
    defaultSpeed: 1.0,
    defaultPitch: 1.05,
    prebuiltVoiceName: 'Zephyr',
    avatarColor: 'from-pink-500 to-rose-700',
    badge: 'Feminina Acolhedora',
  },
];

export function getVoiceById(id: string): VoiceStyle {
  return VOICE_STYLES.find((v) => v.id === id) || VOICE_STYLES[0];
}
